define(function () {
  return [
    ['author', 'string'],
    ['biblEditionStatement', 'string'],
    ['corpusAuthor', 'string'],
    ['corpusEditor', 'string'],
    ['corpusSigle', 'string'],
    ['corpusSubTitle', 'string'],
    ['corpusTitle', 'string'],
    ['creationDate', 'date'],
    ['docAuthor', 'string'],
    ['docEditor', 'string'],
    ['docSigle', 'string'],
    ['docSubTitle', 'string'],
    ['docTitle', 'string'],
    ['editor', 'string'],
    ['fileEditionStatement', 'string'],
    ['keywords', 'string'],
    ['language', 'string'],
    ['license', 'string'],
    ['pages', 'string'],
    ['pubDate', 'date'],
    ['publisher', 'string'],
    ['pubPlace', 'date'],
    ['reference', 'string'],
    ['subTitle', 'string'],
    ['textClass', 'string'],
    ['textColumn', 'string'],
    ['textDomain', 'string'],
    ['textSigle', 'string'],
    ['textType', 'string'],
    ['textTypeArt', 'string'],
    ['textTypeRef', 'string'],
    ['title', 'string']
  ]
});
