define(["hint/foundries"], function (ah) {
  ah["-"].push(
    ["DRuKoLa", "drukola/", "Lemma, Morphology, Part-of-Speech"]
  );

  ah["drukola/"] = [
    ["Lemma", "l="],
    ["Morphology", "m="],
    ["Part-of-Speech", "p="]      
  ];

  ah["drukola/m="] =  [
    ["CTAG", "ctag:"]
  ];

  ah["drukola/m=ctag:"] = [
    ["A","a ","Adjective"],
    ["Y","y ","Abbreviation"],
    ["AN","an ","Adjective, Indefinite"],
    ["APRY","apry ","Adjective, Plural, Direct, Definite"],
    ["APN","apn ","Adjective, Plural, Indefinite"],
    ["APOY","apoy ","Adjective, Plural, Oblique, Definite"],
    ["APON","apon ","Adjective, Plural, Oblique, Indefinite"],
    ["ASRY","asry ","Adjective, Singular, Direct, Definite"],
    ["ASN","asn ","Adjective, Singular, Indefinite"],
    ["ASOY","asoy ","Adjective, Singular, Oblique, Definite"],
    ["ASON","ason ","Adjective, Singular, Oblique, Indefinite"],
    ["ASVY","asvy ","Adjective, Singular, Vocative, Definite"],
    ["ASVN","asvn ","Adjective, Singular, Vocative, Indefinite"],
    ["R","r ","Adverb"],
    ["RC","rc ","Adverb, Portmanteau"],
    ["TS","ts ","Article, Definite or Possessive, Singular"],
    ["TP","tp ","Article, Indefinite or Possessive, Plural"],
    ["TPR","tpr ","Article, non-Possessive, Plural, Direct"],
    ["TPO","tpo ","Article, non-Possessive, Plural, Oblique"],
    ["TSR","tsr ","Article, non-Possessive, Singular, Direct"],
    ["TSO","tso ","Article, non-Possessive, Singular, Oblique"],
    ["NPRY","npry ","Common Noun, Plural, Direct, Definite"],
    ["NPN","npn ","Common Noun, Plural, Indefinite"],
    ["NPOY","npoy ","Common Noun, Plural, Oblique, Definite"],
    ["NPVY","npvy ","Common Noun, Plural, Vocative, Definite"],
    ["NN","nn ","Common Noun, singular"],
    ["NSY","nsy ","Common Noun, Singular, Definite"],
    ["NSRY","nsry ","Common Noun, Singular, Direct, Definite"],
    ["NSRN","nsrn ","Common Noun, Singular, Direct, Indefinite"],
    ["NSN","nsn ","Common Noun, Singular, Indefinite"],
    ["NSOY","nsoy ","Common Noun, Singular, Oblique, Definite"],
    ["NSON","nson ","Common Noun, Singular, Oblique, Indefinite"],
    ["NSVY","nsvy ","Common Noun, Singular, Vocative, Definite"],
    ["NSVN","nsvn ","Common Noun, Singular, Vocative, Indefinite"],
    ["CR","cr ","Conjunctio, portmanteau"],
    ["C","c ","Conjunction"],
    ["QF","qf ","Future Particle"],
    ["QN","qn ","Infinitival Particle"],
    ["I","i ","Interjection"],
    ["QZ","qz ","Negative Particle"],
    ["M","m ","Numeral"],
    ["PP","pp ","Personal Pronoun"],
    ["PPP","ppp ","Personal Pronoun, Plural"],
    ["PPPA","pppa ","Personal Pronoun, Plural, Acc."],
    ["PPPD","pppd ","Personal Pronoun, Plural, Dative"],
    ["PPPR","pppr ","Personal Pronoun, Plural, Direct"],
    ["PPPO","pppo ","Personal Pronoun, Plural, Oblique"],
    ["PPS","pps ","Personal Pronoun, Singular"],
    ["PPSA","ppsa ","Personal Pronoun, Singular, Accusative"],
    ["PPSD","ppsd ","Personal Pronoun, Singular, Dative"],
    ["PPSR","ppsr ","Personal Pronoun, Singular, Direct"],
    ["PPSN","ppsn ","Personal Pronoun, Singular, Nominative"],
    ["PPSO","ppso ","Personal Pronoun, Singular, Oblique"],
    ["S","s ","Preposition"],
    ["DMPR","dmpr ","Pronoun or Determiner, Demonstrative, Plural, Direct"],
    ["DMPO","dmpo ","Pronoun or Determiner, Demonstrative, Plural, Oblique"],
    ["DMSR","dmsr ","Pronoun or Determiner, Demonstrative, Singular, Direct"],
    ["DMSO","dmso ","Pronoun or Determiner, Demonstrative, Singular, Oblique"],
    ["PS","ps ","Pronoun or Determiner, Poss or Emph"],
    ["PSS","pss ","Pronoun or Determiner, Poss or Emph, Singular"],
    ["RELR","relr ","Pronoun or Determiner, Relative, Direct"],
    ["RELO","relo ","Pronoun or Determiner, Relative, Oblique"],
    ["NP","np ","Proper Noun"],
    ["PI","pi ","Quantifier Pronoun or Determiner"],
    ["PXA","pxa ","Reflexive Pronoun, Accusative"],
    ["PXD","pxd ","Reflexive Pronoun, Dative"],
    ["X","x ","Residual"],
    ["QS","qs ","Subjunctive Particle"],
    ["VA","va ","Verb, Auxiliary"],
    ["VA1","va1 ","Verb, Auxiliary, 1st person"],
    ["VA2P","va2p ","Verb, Auxiliary, 2nd person, Plural"],
    ["VA2S","va2s ","Verb, Auxiliary, 2nd person, Singular"],
    ["VA3","va3 ","Verb, Auxiliary, 3rd person"],
    ["VA3P","va3p ","Verb, Auxiliary, 3rd person, Plural"],
    ["VA3S","va3s ","Verb, Auxiliary, 3rd person, Singular"],
    ["VA1P","va1p ","Verb, Auxiliary,1st person, Plural"],
    ["VA1S","va1s ","Verb, Auxiliary,1st person, Singular"],
    ["VG","vg ","Verb, Gerund"],
    ["VN","vn ","Verb, Infinitive"],
    ["V1","v1 ","Verb, Main, 1st person"],
    ["V2","v2 ","Verb, Main, 2nd person"],
    ["V3","v3 ","Verb, Main, 3rd person"],
    ["VPPF","vppf ","Verb, Participle, Plural, Feminine"],
    ["VPPM","vppm ","Verb, Participle, Plural, Masculine"],
    ["VPSF","vpsf ","Verb, Participle, Singular, Feminine"],
    ["VPSM","vpsm ","Verb, Participle, Singular, Masculine"]
  ];
});
