define(function () {
  // http://www.coli.uni-saarland.de/projects/sfb378/negra-corpus/negra-corpus.html
  // http://www.coli.uni-saarland.de/projects/sfb378/negra-corpus/kanten.html
  return [
    ["AC","AC ","adpositional case marker"],
    ["ADC","ADC ","adjective component"],
    ["AMS","AMS ","measure argument of adj"],
    ["APP","APP ","apposition"],
    ["AVC","AVC ","adverbial phrase component"],
    ["CC","CC ","comparative complement"],
    ["CD","CD ","coordinating conjunction"],
    ["CJ","CJ ","conjunct"],
    ["CM","CM ","comparative concjunction"],
    ["CP","CP ","complementizer"],
    ["DA","DA ","dative"],
    ["DH","DH ","discourse-level head"],
    ["DM","DM ","discourse marker"],
    ["GL","GL ","prenominal genitive"],
    ["GR","GR ","postnominal genitive"],
    ["HD","HD ","head"],
    ["JU","JU ","junctor"],
    ["MC","MC ","comitative"],
    ["MI","MI ","instrumental"],
    ["ML","ML ","locative"],
    ["MNR","MNR ","postnominal modifier"],
    ["MO","MO ","modifier"],
    ["MR","MR ","rhetorical modifier"],
    ["MW","MW ","way (directional modifier)"],
    ["NG","NG ","negation"],
    ["NK","NK ","noun kernel modifier"],
    ["NMC","NMC ","numerical component"], 
    ["OA","OA ","accusative object"],
    ["OA2","OA2 ","second accusative object"], 
    ["OC","OC ","clausal object"],
    ["OG","OG ","genitive object"], 
    ["PD","PD ","predicate"],
    ["PG","PG ","pseudo-genitive"],
    ["PH","PH ","placeholder"],
    ["PM","PM ","morphological particle"],
    ["PNC","PNC ","proper noun component"], 
    ["RC","RC ","relative clause"],
    ["RE","RE ","repeated element"],
    ["RS","RS ","reported speech"],
    ["SB","SB ","subject"],
    ["SBP","SBP ","passivised subject (PP)"], 
    ["SP","SP ","subject or predicate"],
    ["SVP","SVP ","separable verb prefix"],
    ["UC","UC ","(idiosyncratic) unit component"], 
    ["VO","VO ","vocative"]
  ];
});
