name: CI Perl Linux
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.36'
          - '5.38'
    name: Perl ${{ matrix.perl-version }} on Linux
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v4
      - name: perl -V
        run: perl -V
      - name: Install dependencies
        run: |
          cpanm --force Module::Pluggable
          cpanm https://github.com/Akron/Mojolicious-Plugin-Localize.git
          cpanm --installdeps .
          cpanm -n Cpanel::JSON::XS EV
      - name: Run tests
        run: prove -lr t/
